In [1]:
#1. Single Layer Perceptron

import numpy as np

X = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([0,0,0,1])   # AND gate

w = np.zeros(2)
b = 0
lr = 0.1

for _ in range(10):
    for i in range(len(X)):
        y_pred = 1 if np.dot(X[i], w) + b >= 0 else 0
        error = y[i] - y_pred
        w += lr * error * X[i]
        b += lr * error

print("Weights:", w)
print("Bias:", b)

Weights: [0.2 0.1]
Bias: -0.20000000000000004


In [2]:
#2.Multilayer Perceptron using Backpropagation

import numpy as np

X = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[0],[1],[1],[0]])

w1 = np.random.rand(2,2)
w2 = np.random.rand(2,1)
lr = 0.1

def sigmoid(x): return 1/(1+np.exp(-x))

for _ in range(5000):
    h = sigmoid(np.dot(X, w1))
    o = sigmoid(np.dot(h, w2))
    w2 += lr * np.dot(h.T, (y-o))
    w1 += lr * np.dot(X.T, np.dot((y-o), w2.T))

print("Output:\n", o)

Output:
 [[0.50206109]
 [0.50200772]
 [0.50107553]
 [0.50125658]]


In [3]:
#3.Neural Network using Scikit-learn

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

X, y = load_iris(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y)

model = MLPClassifier(max_iter=500)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 0.9473684210526315
Confusion Matrix:
 [[12  0  0]
 [ 0 15  1]
 [ 0  1  9]]


c:\Users\priya\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(


In [4]:
#4.Genetic Algorithm for Function Optimization

import random

pop = [random.uniform(-10,10) for _ in range(10)]

def fitness(x): return -x**2 + 10

for _ in range(20):
    pop = sorted(pop, key=fitness, reverse=True)
    p1, p2 = pop[0], pop[1]
    child = (p1 + p2)/2 + random.uniform(-0.1,0.1)
    pop[-1] = child

print("Best Solution:", pop[0])

Best Solution: 0.0012884624286402732


In [5]:
#5.Genetic Algorithm for Feature Selection

import random

features = 5
pop = [[random.randint(0,1) for _ in range(features)] for _ in range(6)]

def fitness(chrom): return sum(chrom)

for _ in range(10):
    pop.sort(key=fitness, reverse=True)
    pop[-1] = pop[0][:]

print("Best Feature Set:", pop[0])

Best Feature Set: [1, 0, 1, 1, 1]
